//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sistemadepedidos.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sistemapedidosEntities1 : DbContext
    {
        public sistemapedidosEntities1()
            : base("name=sistemapedidosEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fornecedor> fornecedor { get; set; }
        public virtual DbSet<pedidos> pedidos { get; set; }
        public virtual DbSet<produto> produto { get; set; }
    }
}
